### ISSUE TITLE
"PedigreeSim.jar" Missing

### ISSUE THREAD

**Issue by dcgerard** [PBR/pedigreeSim#1]
Hey there! I was interested in trying out PedigreeSim. The instructions state to run:
``` bash
java -jar "PedigreeSim.jar"
```
But I can't seem to find "PedigreeSim.jar" in the repo.
Thanks!

**Comment by RoelandV** [comment]
Hi.

Here is the compiled version of PedigreeSim. This used to be downloadable from our PedigreeSim website, I see that this download link has disappeared. Sorry for that.

Regards,
Roeland Voorrips

Wageningen University & Research - Plant Breeding
P.O. Box 386
6700 AJ Wageningen
The Netherlands

Phone +31 317 481061
Mailto:roeland.voorrips@wur.nl<mailto:roeland.voorrips@wur.nl>

**Comment by andreaswallberg** [comment]
Same here. I can not find PedigreeSim.jar.

**Comment by RoelandV** [comment]
Hi,
If you send me your email address I’ll send you a download link.
Regards,
Roeland Voorrips

**Comment by RoelandV** [comment]
The jar file and the lib folder are in the PedigreeSim v2.1_compiled.zip file
